steps:
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  args:
  - gcloud
  - functions
  - deploy
  - net-salary-calculator
  - --region=europe-west1
  - --source=.
  - --trigger-http
  - --runtime=python311
  - --gen2
  - --service-account=net-salary-calculator-sa@real-estate-analyser-dv.iam.gserviceaccount.com
  - --run-service-account=net-salary-calculator-sa@real-estate-analyser-dv.iam.gserviceaccount.com
  - --entry-point=get_net_salary
  - --max-instances=10
  - --set-secrets=TBOT_TOKEN=tbot-net-salary-token:1
  - --set-env-vars=REGION=${_REGION},CHAT_ID=${_CHAT_ID}
  - --timeout=540s