name: Deploy Cloud Function

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Google Cloud SDK
      uses: docker://google/cloud-sdk:alpine
      with:
        entrypoint: /bin/sh
        args: -c echo $GCP_SA_KEY /tmp/keyfile.json && gcloud auth activate-service-account --key-file=/tmp/keyfile.json'
      env:
        GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}

    - name: Deploy Cloud Function
      run: |
        echo "Hello world!"
        # gcloud functions deploy yourFunctionName \
        #   --runtime python311 \
        #   --trigger-http \
        #   --allow-unauthenticated \
        #   --project $GCP_PROJECT_ID
      env:
        GCP_PROJECT_ID: ${{ env.GCP_PROJECT_ID }}

